name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - '2.7'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
        pytest-version:
          - 4
          - 5
          - 6
        exclude:
          # pytest >= 5.x.x doesn't support Python 2.7
          - os: ubuntu-latest
            python-version: 2.7
            pytest-version: 5
          - os: ubuntu-latest
            python-version: 2.7
            pytest-version: 6
          - os: windows-latest
            python-version: 2.7
            pytest-version: 5
          - os: windows-latest
            python-version: 2.7
            pytest-version: 6

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}, pytest ${{ matrix.pytest-version }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Run test
      run: tox
      env:
        PLATFORM: ${{ matrix.os }}
        PYTEST_MAJOR_VERSION: ${{ matrix.pytest-version }}
        PYTEST_PLUGINS: pytest_github_actions_annotate_failures

  post-test:
    name: All tests passed
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo ok
